stm32duino/STM32Ethernet

README.md, src/STM32Ethernet.cpp, src/STM32Ethernet.h, src/utility/stm32_eth.c
I added an update function to the Ethernet class to remove the dependency inside the main.cpp.
The library is now completely independent of the core.
The function update() updates the LwIP stack also.
=> Remove dependency with the core

src/EthernetClient.cpp, src/utility/stm32_eth.c, src/utility/stm32_eth.h
This PR should fix #3 
- Ethernet scheduler called by timer every 1ms
- function close client reworked
To test this PR please add `#define DEFAULT_ETHERNET_TIMER TIM6` in lwipopts.h
The issue #4 is also fixed:
- init sequence is done only once even if `begin()` is called several time.
=> Fix issue #3 and #4

README.md, library.properties, src/lwipopts.h, src/lwipopts_default.h
The LwIP has several user defined options, which is specified from within the `lwipopts.h` file.
Provide a default user defined options file named `lwipopts_default.h`.
User can provide his own defined options at sketch level by adding his configuration in a file named `STM32lwipopts.h`.
=> Default lwipopts.h to avoid embed it in the core and allow easiest user config

AUTHORS, README.md, examples/AdvancedChatServer/AdvancedChatServer.ino, examples/BarometricPressureWebServer/BarometricPressureWebServer.ino, examples/ChatServer/ChatServer.ino, examples/DhcpAddressPrinter/DhcpAddressPrinter.ino, examples/DhcpChatServer/DhcpChatServer.ino, examples/TelnetClient/TelnetClient.ino, examples/UDPSendReceiveString/UDPSendReceiveString.ino, examples/UdpNtpClient/UdpNtpClient.ino, examples/WebClient/WebClient.ino, examples/WebClientRepeating/WebClientRepeating.ino, examples/WebServer/WebServer.ino, keywords.txt, src/STM32Ethernet.cpp, src/STM32Ethernet.h
- 1. This PR supports the internal MAC address like on mbed
- 2. Changed init procedure like on Ethernet3 (https://github.com/sstaub/Ethernet3) library, it is now `Ethernet.begin(ip, subnet, gateway, dns)` which is more common
- tested with STM32F429 Nucleo
- tested with STM32F746 Discovery
- updated readme.md and examples
=> MAC support

src/EthernetClient.cpp, src/EthernetServer.cpp, src/EthernetServer.h
When iterating we make sure client's socket is not closing
since _tcp_client remains after close.
This was tested on nuleo-f767zi using project webthing-arduino
Change-Id: Ie465fe59009c33957dad97f1c70b4dc3af3b2ebe
Signed-off-by: Philippe Coval <p.coval@samsung.com>
=> client: Fix bool operator on init and ongoing use

library.json
This file addition includes the support for the PlatformIO library manager.
With some adaptations it can used for all the libraries.
After making the PR, the library can be registered. I can do this.
https://docs.platformio.org/en/latest/librarymanager/creating.html#register
=> Support for PlatformIO library manager

src/utility/stm32_eth.cpp
Use of [HardwareTimer library](https://github.com/stm32duino/Arduino_Core_STM32/pull/576) for STM32duino_STM32Ethernet.
=> Update STM32duino_STM32Ethernet library to use HardwareTimer library

src/EthernetClient.cpp
This patch allows the WebClientRepeating example to work. I suspect this will also fix #22. Also fixes one of the SSLClient examples.
Without this patch, only the first connect succeeds. The following attempts fail because _tcp_client is not NULL.
=> Allocate the TCP client when needed.

src/STM32Ethernet.cpp, src/STM32Ethernet.h, src/utility/stm32_eth.cpp, src/utility/stm32_eth.h
Also remove 2 printf debug. Should close #19. Here is the test code.
```
#include <LwIP.h>
#include <STM32Ethernet.h>
// Initialize the Ethernet client library
// with the IP address and port of the server
// that you want to connect to (port 80 is default for HTTP):
EthernetClient client;
void setup() {
// Open serial communications and wait for port to open:
Serial.begin(115200);
Serial.println("Ethernet.linkStatus test");
while (!Serial) {
; // wait for serial port to connect. Needed for native USB port only
}
// start the Ethernet connection:
if (Ethernet.begin() == 0) {
Serial.println("Failed to configure Ethernet using DHCP");
// no point in carrying on, so do nothing forevermore:
for (;;)
;
}
}
void loop () {
if (Ethernet.linkStatus() == Unknown) {
Serial.println("Link status …
```
=> Add Ethernet.linkStatus

src/STM32Ethernet.cpp, src/utility/ethernetif.c, src/utility/ethernetif.h, src/utility/stm32_eth.cpp, src/utility/stm32_eth.h
Hi @gdsports 
could you review/test this PR please.
Thanks in advance
=> Update Ethernet.linkStatus to handle Unknown status

src/EthernetUdp.cpp, src/EthernetUdp.h
UDP connected sockets are limited to commuinicating with one host and port. Should fix #20.
=> Use UDP unconnected sockets

src/utility/ethernetif.cpp
Rework ethernet cable hotplug detection
Mimic NUCLEO-H743ZI Cube Application: LwIP_HTTP_Server_Netconn_RTOS
Fixes #42
=> Rework ethernet cable hotplug detection

src/lwipopts.h, src/lwipopts_default.h, src/utility/ethernetif.cpp, src/utility/stm32_eth.cpp, src/utility/stm32_eth.h
HardwareTimer: remove usage of TIMER_OUTPUT_COMPARE mode
With introduction of PR
https://github.com/stm32duino/Arduino_Core_STM32/pull/1247
Usage of TIMER_OUTPUT_COMPARE becomes obsolete.
Note: removing setMode(1, TIMER_OUTPUT_COMPARE)
also works before PR #1247.
=> HardwareTimer: remove usage of TIMER_OUTPUT_COMPARE mode

src/EthernetClient.cpp, src/EthernetClient.h, src/utility/stm32_eth.cpp
when DHCP fails the static IP can be applied without problem
adding timeout to client connection
=> if DHCP fails the static IP can be applied without problem

src/EthernetServer.cpp
Fix : Wrong _tcp_client[] array initialization
Former "_tcp_client[MAX_CLIENT] = {};" tries to initialize
the array element with index MAX_CLIENT,
which is out of array range [0 .. (MAX_CLIENT-1)]
Fixes warning:
warning: array subscript 32 is above array bounds of 'tcp_struct* [32]' [-Warray-bounds]
Instead initialize each element of the array one by one.
Signed-off-by: Alexandre Bourdiol <alexandre.bourdiol@st.com>
=> Fix : Wrong _tcp_client[] array initialization

src/EthernetServer.cpp, src/EthernetServer.h
I use the `EthernetServer `class but I must read the port to be used from a configuration file on an SD Card at runtime.
As the port is optionally defined in the constructor and only used in the `begin()` function, I added a `begin(uint16_t port)` function to set port if needed,
=> feat: Add function to define port of EthernetServer at runtime

src/utility/stm32_eth.cpp
fix: set Ethernet Timer priority to 15
Aim is to have Ethernet Timer priority lower (higher value)
than Systick (including FreeRTOS usecase)
This PR comes with https://github.com/stm32duino/STM32FreeRTOS/pull/57 in order to
Fixes #65
=> fix: set Ethernet Timer priority to 15

keywords.txt, src/EthernetClient.cpp, src/EthernetClient.h
Rename it `setConnectionTimeout` to match Arduino Ethernet API.
https://www.arduino.cc/reference/en/libraries/ethernet/client.setconnectiontimeout/
Fixes #72
=> fix(client): setTimeout shadows Stream.setTimeout

src/EthernetClient.cpp
As listed in issue #75, there is an error that caused large memory usage in the `EthernetClient`module. These changes fix the mentioned memory bug.
=> Fixing bug that caused large memory consumption

README.md, src/EthernetServer.cpp, src/EthernetServer.h
* bool operator:
https://www.arduino.cc/reference/en/libraries/ethernet/ifserver/
* `end()`:
Not officially documented. Pay attention, when `end()` is called, the socket is not close immediately. The tcp connection will come into `TCP_WAIT`,  after few minutes (~2 minutes) the connection will close completely and free the socket.
So calling `begin()` during this time frame after the `end() ` will silently failed and have to check thanks the bool operator if the server is ready or not. If not then call again `begin()`.
For `TCP_WAIT` ref: https://github.com/stm32duino/LwIP/blob/4de72d4b92ebf1ac5ce5efe7c331c0af6d52cca3/src/core/tcp.c#L1446C11-L1446C11
Fixes #73.
=> feat(server): add bool operator and end() api

src/STM32Ethernet.cpp, src/STM32Ethernet.h
EthernetClass - add setDnsServerIP as in Arduino Ethernet library
[overview](https://github.com/JAndrassy/Arduino-Networking-API/blob/main/ArduinoNetAPILibs.md#legacy-ethernet-getters-and-setters) of Ethernet legacy getters and setters in Arduino Ethernet libraries
=> EthernetClass - add setDnsServerIP as in Arduino Ethernet library

src/EthernetClient.cpp
All examples have `if (client.coonect(server, port)`, but `getHostName` doesn't return only 1 or 0, so `connect` can't return the return value of getHostName.
=> EthernetClient.connect - return only 1 or 0

README.md, keywords.txt, src/Dhcp.cpp, src/STM32Ethernet.cpp, src/STM32Ethernet.h, src/utility/ethernetif.cpp, src/utility/ethernetif.h, src/utility/stm32_eth.cpp, src/utility/stm32_eth.h
References:
https://www.arduino.cc/reference/en/libraries/ethernet/ethernet.macaddress/ https://www.arduino.cc/reference/en/libraries/ethernet/ethernet.setmacaddress/
> [!Important]
> Pay attention that `setMACAddress()` have to be called before `Begin()`.
> Else new MAC will be ignored.
This PR also fixes with the default MAC address usage. It is used only if one or more `MAC_ADDRx` defined.
The MAC address is also correct at all level.
Fixes #81
```C++
#include <LwIP.h>
#include <STM32Ethernet.h>
byte mac[] = { 0xDE, 0xAD, 0xBE, 0xEF, 0xFE, 0xED };
IPAddress ip(192, 168, 1, 69);
void printMacAddress(byte* macBuffer) {
Serial.print("The MAC address is: ");
for (byte octet = 0; octet < 6; octet++) {
Serial.printf("%02X", macBuffer[octet]);
if (octet < 5) {
Serial.print('-');
} else { …
```
=> fix: align MAC address api with Arduino reference

src/EthernetClient.cpp, src/EthernetUdp.cpp
=> Fix: peek() function always return first byte of data
